### ISSUE TITLE
Cannot find module 'child_process'

### ISSUE THREAD

**Issue by mochini** [versatica/mediasoup-client-aiortc#11]
when I install this library and try to include it in my user interface file, like so:

`import { version, createWorker, Worker, WorkerLogLevel } from 'mediasoup-client-aiortc'`

and I get the following error in my browser:

`Uncaught Error: Cannot find module 'child_process'`

I see that it requires 'child_process' here:

https://github.com/versatica/mediasoup-client-aiortc/blob/v3/src/Worker.ts#L3

But I don't see it included in the package.json. Could that be the problem?

Thanks in advance

**Comment by ibc** [comment]
README.md:

> mediasoup-client handler for aiortc Python library. Suitable for building Node.js applications that connect to a mediasoup server using WebRTC and exchange real audio, video and DataChannel messages with it in both directions.

**Comment by mochini** [comment]
Got it! Not meant for the browser…

Thanks...
