### ISSUE TITLE
Cannot find starting point of mediasoup-client-aiortc

### ISSUE THREAD

**Issue by harshacoolkaru** [versatica/mediasoup-client-aiortc#12]
We have a mediasoup server running in vm now we want to connect our raspberry pi as a client.
Instructions I have followed so far:
1) I have installed all the prerequisites for mediasoup aiortc
2) PIP3=/home/me/bin/pip npm install --save mediasoup-client-aiortc (it was installed successfully by changing the pip path)
3) npm install (successfully installed required packages)
4) I have also build type script using (npm run typescript:build)

Now there is an issue that cannot find the starting point. In the example they have mentioned my_app.js file but there is no file.
So, want to know how can I start client in raspberrypi

**Comment by ibc** [comment]
Please use the mediasoup forum for questions.
