### ISSUE TITLE
MediaPlayer Error 

### ISSUE THREAD

**Issue by fengkouxiaozhu** [versatica/mediasoup-client-aiortc#14]
When I use MediaPlayer('video=Integrated Camera')   I met  a error  av.error.FileNotFoundError:  No such file or directory: 'video=Integrated Camera'  How Can I solve the problems !  thanks!

**Comment by jmillan** [comment]
This error is fired by `av`(ffmpeg) from  https://github.com/aiortc/aiortc. Not related to `mediasoup-client-aiortc`.

The error message seems quite descriptive though.
