### ISSUE TITLE
Handler's `receive` should accept an array

### ISSUE THREAD

**Issue by hkirat** [versatica/mediasoup-client-aiortc#15]
After the change in https://github.com/versatica/mediasoup-client/pull/191
we might need to add the change [here](https://github.com/versatica/mediasoup-client-aiortc/blob/v3/lib/Handler.js#L352) as well

**Comment by jmillan** [comment]
Please feel free to submit a PR.

**Comment by hkirat** [comment]
Filed for a PR [here](https://github.com/versatica/mediasoup-client-aiortc/pull/17) !
