### ISSUE TITLE
safeEmitAsPromise is renamed

### ISSUE THREAD

**Issue by h3poteto** [versatica/mediasoup-client-aiortc#16]
When I use this library with `mediasoup-client@3.6.53`, it says an error.

```
await this.safeEmitAsPromise('@connect', { dtlsParameters });
                   ^

TypeError: this.safeEmitAsPromise is not a function
```

When I use it with `mediasoup-client@3.6.52`, it works fine.

In the latest release of `mediasoup-client`, `safeEmitAsPromise` method is removed.
https://github.com/versatica/mediasoup-client/compare/3.6.52...3.6.53

**Comment by jmillan** [comment]
Please feel free to submit a PR.

**Comment by h3poteto** [comment]
Resolved: https://github.com/versatica/mediasoup-client-aiortc/commit/e45dc89b2dfa709cbeabff46c686fdb75a21f823
