### ISSUE TITLE
Crash when using MediaPlayer

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client-aiortc#4]
* Issue reported `aiortc` project: https://github.com/aiortc/aiortc/issues/274

**Comment by ibc** [comment]
Fixed in https://github.com/aiortc/aiortc/pull/287. Waiting for release.

**Comment by jlaine** [comment]
`aiortc` 0.9.26 will be uploaded to pypi with the fix for this issue as soon as this build completes:

https://travis-ci.com/aiortc/aiortc/builds/150390692

**Comment by ibc** [comment]
Done :)
Thanks a lot, @jlaine
